"""add package provider_params

Revision ID: 1940cc4610b3
Revises: a7d7df6a7683
Create Date: 2026-07-29 17:26:55.452457

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '1940cc4610b3'
down_revision: str | Sequence[str] | None = 'a7d7df6a7683'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('provider_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'provider_params')
    # ### end Alembic commands ###
