"""initial schema

Revision ID: a7d7df6a7683
Revises:
Create Date: 2026-07-27 15:24:03.283868

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'a7d7df6a7683'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carriers',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('tracking_url_template', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carriers'))
    )
    op.create_index(op.f('ix_carriers_code'), 'carriers', ['code'], unique=True)
    op.create_table('providers',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('OFFICIAL_API', 'SCRAPER', 'AGGREGATOR', name='provider_kind', native_enum=False, length=20), nullable=False),
    sa.Column('requires_credentials', sa.Boolean(), nullable=False),
    sa.Column('supports_all_carriers', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('setup_guide', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers'))
    )
    op.create_index(op.f('ix_providers_code'), 'providers', ['code'], unique=True)
    op.create_table('shops',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shops'))
    )
    op.create_index(op.f('ix_shops_code'), 'shops', ['code'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('packages',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tracking_number', sa.String(length=120), nullable=False),
    sa.Column('carrier_id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'EXCEPTION', 'UNKNOWN', name='package_status', native_enum=False, length=20), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], name=op.f('fk_packages_carrier_id_carriers')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_packages_provider_id_providers')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_packages_shop_id_shops')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_packages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packages'))
    )
    op.create_index('ix_packages_next_check_at_active', 'packages', ['next_check_at'], unique=False, postgresql_where=sa.text('NOT is_archived'))
    op.create_index(op.f('ix_packages_tracking_number'), 'packages', ['tracking_number'], unique=False)
    op.create_index('ix_packages_user_id_is_archived', 'packages', ['user_id', 'is_archived'], unique=False)
    op.create_table('provider_carrier_exclusion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('carrier_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], name=op.f('fk_provider_carrier_exclusion_carrier_id_carriers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_carrier_exclusion_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_carrier_exclusion')),
    sa.UniqueConstraint('provider_id', 'carrier_id', name=op.f('uq_provider_carrier_exclusion_provider_id'))
    )
    op.create_table('provider_carrier_support',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('carrier_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], name=op.f('fk_provider_carrier_support_carrier_id_carriers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_carrier_support_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_carrier_support')),
    sa.UniqueConstraint('provider_id', 'carrier_id', name=op.f('uq_provider_carrier_support_provider_id'))
    )
    op.create_table('shop_carrier_hints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('carrier_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], name=op.f('fk_shop_carrier_hints_carrier_id_carriers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_shop_carrier_hints_shop_id_shops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_carrier_hints')),
    sa.UniqueConstraint('shop_id', 'carrier_id', name=op.f('uq_shop_carrier_hints_shop_id'))
    )
    op.create_table('user_provider_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_secret', sa.String(length=4000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_user_provider_credentials_provider_id_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_provider_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_provider_credentials')),
    sa.UniqueConstraint('user_id', 'provider_id', name=op.f('uq_user_provider_credentials_user_id'))
    )
    op.create_table('tracking_events',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'EXCEPTION', 'UNKNOWN', name='package_status', native_enum=False, length=20), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_tracking_events_package_id_packages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_tracking_events_provider_id_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracking_events')),
    sa.UniqueConstraint('package_id', 'occurred_at', 'description', name=op.f('uq_tracking_events_package_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracking_events')
    op.drop_table('user_provider_credentials')
    op.drop_table('shop_carrier_hints')
    op.drop_table('provider_carrier_support')
    op.drop_table('provider_carrier_exclusion')
    op.drop_index('ix_packages_user_id_is_archived', table_name='packages')
    op.drop_index(op.f('ix_packages_tracking_number'), table_name='packages')
    op.drop_index('ix_packages_next_check_at_active', table_name='packages', postgresql_where=sa.text('NOT is_archived'))
    op.drop_table('packages')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shops_code'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_providers_code'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_carriers_code'), table_name='carriers')
    op.drop_table('carriers')
    # ### end Alembic commands ###
